security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        main:
            pattern: ^/
            oauth:
                resource_owners:
                    facebook:           "/secured/login_facebook"
                    google:           "/secured/login_google"
                login_path:        fos_user_security_login
                failure_path:      fos_user_security_login

                oauth_user_provider:
                    service: my.oauth_aware.user_provider.service
            anonymous:    true